import Node from "./Nodes/Node";
import styles from "./MainPage.module.css";
const MainPage = () => {
  return (
    <div className={styles.nodesWraper}>
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
      <Node />
    </div>
  );
};

export default MainPage;
